In [1]:
import numpy as np
import pandas as pd

In [2]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [3]:
np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]]).diagonal().mean()

1.0

In [4]:
np.random.randint(0, 5, (3, 3))

array([[0, 1, 2],
       [3, 1, 0],
       [4, 3, 1]])

In [5]:
np.random.randint(0, 6, (3, 3))

array([[5, 5, 2],
       [0, 5, 5],
       [3, 2, 4]])

In [6]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1, 14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [9]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [10]:
round(big_secret[:, -1].sum(), 2)

3154.33

In [11]:
round(big_secret[:, :5].diagonal().sum(), 2)

121.37

In [12]:
y = 1
for x in big_secret[:, -5:].diagonal():
    y *= x
y

341505315559.2347

In [13]:
big_secret[::2, ::2 ] = -1
big_secret[1::2, 1::2 ] = 1

In [14]:
big_secret[:, :5].diagonal().sum()

-1.0

In [15]:
y = 1
for x in big_secret[:, -5:].diagonal():
    y *= x
y

-1.0

In [16]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [17]:
great_secret.shape

(100, 3)

In [18]:
round(np.cos(great_secret[0]).sum(), 2)

0.16

In [19]:
great_secret[great_secret > 50].sum()

5470.0

In [20]:
great_secret.reshape(1, 300)[0, 150]

7.0710678118654755

In [21]:
round(np.sort(great_secret, axis=0)[-1, :].sum(), 2)

115.12

In [22]:
students = np.array([
    [1, 	135, 	34, 	4,],
    [2, 	160, 	43, 	5,],
    [3, 	163, 	40, 	4.3,],
    [4, 	147, 	44, 	5,],
    [5, 	138, 	41, 	4.7,],
    [6, 	149, 	54, 	3.9,],
    [7, 	136, 	39, 	4.2,],
    [8, 	154, 	48, 	4.9,],
    [9, 	137, 	35, 	3.7,],
    [10, 	165, 	60, 	4.6,],
])

In [23]:
np.mean(students[:,-1])

4.430000000000001

In [24]:
np.median(students[:,-1])

4.449999999999999

In [25]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

In [26]:
np.median(students[:,2])

42.0

In [27]:
round(np.mean(students[:,2]) - np.median(students[:,2]), 1)

1.8

In [28]:
np.corrcoef(students[:,1], students[:,2])

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [29]:
np.corrcoef(students[:,1:], rowvar=False)

array([[1.        , 0.64314431, 0.46293714],
       [0.64314431, 1.        , 0.29801325],
       [0.46293714, 0.29801325, 1.        ]])

In [30]:
np.std(students[:,-1])

0.4517742799230607

In [31]:
np.var(students[:,2])

60.36

In [32]:
np.ones((5,10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [33]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [34]:
my_array[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [35]:
my_sin = np.sin(my_array)

In [36]:
round(my_sin.sum(), 3)

-0.058

In [37]:
my_sin[1:4,1:4] = 1

In [38]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [39]:
round(my_sin.sum(), 3)

7.572

In [45]:
round(my_sin[:, :4].reshape(10, 2)[:, :1].sum(), 3)

2.406

In [49]:
bigdata = np.array([x**2 for x in range(100, 1000) if x % 2 != 0])

In [50]:
np.median(bigdata)

302501.0

In [52]:
round(np.std(bigdata))

292095.0

In [53]:
np.corrcoef(bigdata[::2], bigdata[1::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])